### PR TITLE
Control Test Folder Selection with Dynamic Workflows

### PR DESCRIPTION
**Pull request by H0R5E**
This PR changes the test folder selection from being hardcoded in the workflow files to being dynamically generated by the new `getTestTargets.m` MATLAB script.

When run, this script will generate two temporary files, which are read by the workflow to populate the folders and includes keys of the strategy matrix. To facilitate this, the required MATLAB toolboxes (referred to as products) for each test folder must now be included in a file called `products.txt`.

For a PR or push, a diff file, generated by the [GrantBirki/git-diff-action](https://github.com/GrantBirki/git-diff-action) action, is passed to `getTestTargets.m` to limit the test folders to those where changes have occurred.

For dispatch events, sent from the WEC-Sim repository, all folders are still tested.

Events on both the main and dev branches are now handled by the same workflow (`process-events.yml`). A [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) is used to reduce code repetition for the test running steps (`run-tests-reusable.yml`).

### CODE REVIEW

**Comment by H0R5E** [comment]
@kmruehl @akeeste, I thought you might like to look at the changes here before I committed them to the branches. Let me know if this new process is OK for you.

**Review by akeeste — COMMENTED** [review]
Thanks @H0R5E and apologies for the delay. 

I follow the changes in this PR and based on this PR's checks it is running as appropriate. The repeatable workflow is also a nice benefit.

One comment from my review: Is Actions caching and reusing the MATLAB installation for each test? It appears like each test spends about [4:20 on Windows](https://github.com/WEC-Sim/WEC-Sim_Applications/actions/runs/9743624397/job/26887570897?pr=63) and [2:30 on ubuntu](https://github.com/WEC-Sim/WEC-Sim_Applications/actions/runs/9743624397/job/26887566410?pr=63) to install MATLAB. We could further decrease our testing time significantly if the MATLAB installation was reused between jobs with the same packages.

**Comment by H0R5E** [comment]
Hi @akeeste, I'm not sure caching is going to work out of the box because I think we will run into [cache thrashing](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy) due to the different toolbox combinations.

I've got a couple of ideas to get around it, but it will take a bit of work. I'd recommend we merge this one, and then I can start another issue/PR cycle about optimizing the MATLAB installations. Is that OK?

**Comment by akeeste** [comment]
@H0R5E agreed we can make the installation caching a different PR. I'll merge this and then let's move to that.

**Pull request merged**
