### PR TITLE
Updating the visualization examples to Paraview 5.9.1

### PR DESCRIPTION
**Pull request by kmruehl**
Updating the visualization examples to Paraview 5.9.1. This PR does the following:
- [x] Updates `*.pvsm` state files for both WEC-Sim_Application cases with Paraview 5.9.1
- [x] Updates README for WEC-Sim_Application cases to specify Paraview 5.9.1 and WEC-Sim v4.2

This PR relates to https://github.com/WEC-Sim/WEC-Sim/pull/595 and https://github.com/WEC-Sim/WEC-Sim/issues/459

### CODE REVIEW

**Comment by kmruehl** [comment]
@cmichelenstrofer or @akeeste can one of you verify that the updated state files are working? Thank you!

**Comment by akeeste** [comment]
@kmruehl Yes I am able to load the new *.pvsm state files for both the OSWEC and the RM3

**Comment by kmruehl** [comment]
@akeeste thank you!

**Review by cmichelenstrofer — APPROVED** [review]
It works, can be merged. Some suggestion for future improvements: 
- Add segment tensions to the one of the RM3 views (maybe make the lines thicker too)
- Remove the specific path "C:/kmruehl/..." from the .pvsm files. "files from state path" will not work either way but at least we are not pushing paths specific to one computer
- Ideally we would create  multiple views without creating multiple copies of the objects (right now there are 3 grounds, 3 waves ,etc.)

**Comment by kmruehl** [comment]
@cmichelenstrofer thank you! Yes, I agree those are great suggestions. I'll open an issue with those suggestions. Looks like I merged the PR right before your review.

**Pull request merged**
