### PR TITLE
Variable hydro demonstrations

### PR DESCRIPTION
**Pull request by akeeste**
This PR adds applications related to variable hydrodynamics.

- [x] working and scripted comparison between variable hydro and passive yaw. Note that BEMIO for this case may take several hours to run due to the number of .h5 files being written.
- [x] add a test for the variable hydro demonstration of passive yaw

Do not attempt creating this hydro data until https://github.com/WEC-Sim/WEC-Sim/pull/1301 is merged

### CODE REVIEW

**Comment by akeeste** [comment]
The tests are currently failing because ``wrapTo180`` is not recognized as a function. I'm not sure why this is. It doesn't appear to come with an additional toolbox. Passive yaw uses this function in pre-processing and has not thrown an error.

**Comment by H0R5E** [comment]
@akeeste, the `products.txt` file needs to go in the top level directory, i.e. `Variable_Hydro/products.txt`. I think the tests are failing because the toolboxes are not being installed.

**Comment by H0R5E** [comment]
So it ran, but the error it is creating now is:

`Unrecognized method, property, or field 'variableHydro' for class 'bodyClass'.`

**Comment by akeeste** [comment]
> So it ran, but the error it is creating now is:
> 
> `Unrecognized method, property, or field 'variableHydro' for class 'bodyClass'.`

Thanks @H0R5E! That fixed the issue. 

This new issue is coming from this PR referencing the dev branch instead of the relevant [open PR ](https://github.com/WEC-Sim/WEC-Sim/pull/1248) on the WEC-Sim repo. This should now pass once that PR is merged into dev. But for now this PR is serving as an working example to test that feature.

**Comment by akeeste** [comment]
@kmruehl A couple more notes on this application:
- I imagine the time required for BEMIO will stand out here. I'm really not sure how many H5 files would be required for other states (variable geometry, etc). There's a pretty wide range in direction needed here as the flap oscillates significantly in yaw about the equilibrium point (50-60 degree range in strong irregular waves). I'm hoping that other states won't require the same discretization but the pre-processing computational expense is something for us to be aware of.
- With so many input files going into the ``body`` variable, saving that data to a .mat file makes it very very large.

**Comment by kmruehl** [comment]
@akeeste perhaps this case should only be run locally, or we need to greatly reduce it

**Pull request merged**
