### PR TITLE
Refactor test workflows

### PR DESCRIPTION
**Pull request by H0R5E**
Test workflows are refactored to split out those triggered by WEC-Sim commits (wec-sim-***-tests) from those triggered by modifications to the applications (changed-tests).

This change is to try and help improve the distinction between the two types of testing workflows both by having distinct files and by using clearer language in the workflow titles and step names.

I also created another reusable workflow for the WEC-Sim triggered tests to avoid code duplication while maintaining distinct workflows and buttons.

Using this PR as a record of the thought process.

### CODE REVIEW

**Comment by H0R5E** [comment]
I've tried to make some improvements since our discussion with @jtgrasb and @akeeste in order to try and make it a bit clearer what is going on. If you think this is OK, I'll merge and then apply directly to the dev branch.

**Comment by kmruehl** [comment]
@H0R5E can you submit this PR into dev? We're planning to tag v6.1 today, so dev will become main shortly. That way we don't have to pull this from main to dev too.

**Comment by H0R5E** [comment]
> @H0R5E can you submit this PR into dev? We're planning to tag v6.1 today, so dev will become main shortly. That way we don't have to pull this from main to dev too.

Yep, I'll close this and do it directly.

**Comment by kmruehl** [comment]
> I've tried to make some improvements since our discussion with @jtgrasb and @akeeste in order to try and make it a bit clearer what is going on. If you think this is OK, I'll merge and then apply directly to the dev branch.

Either way, it seems like we posted a basically the same time :)

**Comment by H0R5E** [comment]
@kmruehl, I did both manually, because the badges wouldn't generate unless the workflows were on the main branch. Note that they are currently grey because these particular workflows won't have run until something happens in the WEC-Sim branches.

**Pull request closed without merging**
