### PR TITLE
Fixing inconsistent sign in the RM3 example

### PR DESCRIPTION
**Pull request by jleonqu**
This is an update to the RM3 example based on this PR in the WEC-Sim repo: [PR #1221](https://github.com/WEC-Sim/WEC-Sim/pull/1221)
Which was based on this Issue from the WEC-Sim repo: [Issue #1218](https://github.com/WEC-Sim/WEC-Sim/issues/1218)

### CODE REVIEW

**Comment by dforbush2** [comment]
This fix works. I do request that the run time is set back to ~400 seconds so that the test cases do not need to run to 2000 s, but the long run is was a good test case (I do not have write access to this fork). 

Ready to merge.

**Comment by akeeste** [comment]
@jleonqu Based on the error message in the runner, it seems there's still an issue with the fix in the PTO-Sim library.

Warning message: 
```  [Warning: Result of power is undefined in 'RM3_cHydraulic_PTO/PTO-Sim/Gas-Charged Hydraulic Accumulator/Math Function1'.]```

The case ends up failing because the simulation goes unstable.

**Comment by jleonqu** [comment]
@akeeste PR [#1236](https://github.com/WEC-Sim/WEC-Sim/pull/1236) from the WEC-Sim repo should fix this issue with the test that is failing.

**Comment by dforbush2** [comment]
I successfully ran this example in windows 2023b... not sure why the test is not passing but can confirm that this works (using the library change in WEC-Sim PR in #1236

**Comment by jleonqu** [comment]
Closing this PR. The PR #60 was created to rebase this PR to the main branch.

**Pull request closed without merging**
