### PR TITLE
Implement GitHub Actions for local pushes to dev

### PR DESCRIPTION
**Pull request by H0R5E**
This PR adds automated testing of the `dev` branch using GitHub Actions. Note that the `testWECCCOMP_Fault_Implementation` test has been set to skip. This should be undone when #20 is merged.

### CODE REVIEW

**Comment by H0R5E** [comment]
@kmruehl, I'm noticing here that the PTO-Sim tests run noticeably slower on the [WEC-Sim `dev` branch](https://github.com/WEC-Sim/WEC-Sim/tree/dev). The tests are identical between the `master` and `dev` branch in [WEC-Sim_Applications](https://github.com/WEC-Sim/WEC-Sim_Applications) but run in 18 minutes using the [WEC-Sim `master` branch](https://github.com/WEC-Sim/WEC-Sim/tree/master) and 30 minutes using the [WEC-Sim `dev` branch](https://github.com/WEC-Sim/WEC-Sim/tree/dev). Is that expected?

**Comment by kmruehl** [comment]
@H0R5E that is not expected. I just created the dev branch off of master and I do not recall any changes to the PTO-Sim cases since then (that were merged into dev). Very strange indeed... However @jleonqu is rewriting PTO-Sim entirely so these tests will be overhauled once we've merged PR https://github.com/WEC-Sim/WEC-Sim/pull/743. Perhaps remove them from the tests entirely for now and then re-add them once PR 743 is merged?

**Comment by H0R5E** [comment]
@kmruehl, it's happening so inconsistently that I'm not sure what the cause is. Could be variance between the runners or perhaps there is some randomization somewhere? I don't think it is necessary to skip the tests, just something to keep an eye on to see if https://github.com/WEC-Sim/WEC-Sim/pull/743 makes any improvements to it.

This is ready to merge now.

**Comment by H0R5E** [comment]
This is blocking me setting up the triggering from [WEC-Sim](https://github.com/WEC-Sim/WEC-Sim), so I'm going to go ahead and merge it.

**Pull request merged**
