### PR TITLE
Bug fixes for WEC-Sim Applications

### PR DESCRIPTION
**Pull request by akeeste**
Final round of bug fixes for WEC-Sim Applications before v6.0 release:
- [x] update MOST pre-processing
   - Remove calls to ``clearvars`` and convert mostIO scripts to functions to prevent variable conflicts
   - Remove TurbSim executable. WEC-Sim shouldn't ship another independent software within it
- [x] add Multiple Wave Headings test and standardize naming within it
- [x] update the call to ``tiledlayout`` in WECCCOMP MPC post processing to work with R2020b
- [x] make paths in the MOST test OS-agnostic
- [x] switch tests to windows --> revert back to linux and instead remove MoorDyn for now. The .so file will be updated at a later date
   - [x] remove all MoorDyn Tests: Paraview and Mooring
- [x]  Remove 2020b tests, update all tests to `latest` version of MATLAB only
- [x] All tests pass

### CODE REVIEW

**Comment by akeeste** [comment]
@jtgrasb @RyanDavies19 MoorDyn 2.0 is now being tested on Linux through GitHub actions. But it seems like the ``.so`` file is causing [MATLAB to crash](https://github.com/WEC-Sim/WEC-Sim_Applications/actions/runs/6539029002/job/17756204428?pr=49#step:11:257). Do either of you have insight? Has the ``.so`` been tested locally?

**Comment by akeeste** [comment]
Test update: There are three failing tests (each on both MATLAB versions with the same errors):
- Mooring (MoorDyn case) --> ``.so`` file is causing MATLAB to crash?
- Paraview (MoorDyn case) --> ``.so`` file is causing MATLAB to crash?
- MOST --> Adam will check and update here

**Comment by jtgrasb** [comment]
Hi Adam,

I apologize for the issues with the .so file. I was able to generate the .so file using the HPC machines, but i wasn't able to test it. Do you know if there's anyone on the WEC-Sim team that uses a linux machine and can generate and test a new .so file?

**Comment by kmruehl** [comment]
Decision to switch tests to run on Windows, and remove *.so file from the MoorDyn repo. Running MoorDyn on Linux will be added to the project board to be resolved after v6 release.

**Review by kmruehl — CHANGES_REQUESTED** [review]
This PR looks good, but we're still having issues with a few of the tests. Those need to be resolved prior to merging

**Comment by kmruehl** [comment]
tests are passing! merging now

**Pull request merged**
