### PR TITLE
Bug fixes for v6.0

### PR DESCRIPTION
**Pull request by akeeste**
This PR fixes various minor bugs the prevent the tests from passing.
- [x] updates the free decay cases to use ``body.adjMassFactor`` instead of ``simu.adjMassFactor``
- [x] updates the MoorDyn input file for the Paraview RM3 application which uses MoorDyn
- [x] updates visualization of the MOST test results
- [x] updates MOST test results to be consistent with their most recent version
- [x] minor linting as I encountered things
- [x] fix issues with one WECCCOMP case and one wave marker case --> source issue, completed in WEC-Sim PR
- [x] Add mean drift test
- [x] standardize naming convention for radiation force options test

Also noting for future reference, that the error "Variable clock_out does not exist" is typically not helpful. Usually the ``clock_out`` variable does not exist because something else prevents Simulink from running.

### CODE REVIEW

**Comment by akeeste** [comment]
I still have an issues with seemingly random Applications (WECCCOMP_fault and Wave_Markers/RM3). When running the WECCCOMP_fault case locally, I see:
* wecSim command + R2023b --> passes
* wecSim command + R2023a --> passes
* TestWECCCOMP + R2023b --> fails
* TestWECCCOMP + R2023a --> fails

The test fails when using both the set-up from ``wecSimAppTest`` and a simple set-up:
```matlab
t = TestWECCCOMP();
results = t.run();
```

**Comment by akeeste** [comment]
Update: the error catching added to wecSim.m to allow MoorDyn 2.0 to work is what is causing the misleading error messages. I'll look at updating this so that the the error itself is thrown after MoorDyn is closed, giving useful debugging information

**Comment by akeeste** [comment]
Of the tests that are currently failing:
- Wave Marker and WECCCOMP will pass once WEC-Sim/WEC-Sim#1136 is merged into dev
- MoorDyn and Paraview RM3 with MoorDyn will continue to fail because we currently do not have a ``.so`` file for MoorDyn 2.0, which is required for Linux. WEC-Sim Applications Tests are currently only running on Linux.

**Review by kmruehl — APPROVED** [review]

**Comment by kmruehl** [comment]
@akeeste I think we should remove the MoorDyn tests from the CI until they are running properly.

**Comment by kmruehl** [comment]
I'm going to merge this and then update the tests directly.

**Pull request merged**
