### PR TITLE
Example for N Waves 

### PR DESCRIPTION
**Pull request by salhus**
This is a reintroduction of PR #42

### CODE REVIEW

**Comment by nathanmtom** [comment]
@salhus Thanks for resubmitting this PR. I've merged you're last PR into WEC-Sim/WEC-Sim for the updated body block. I will wait to see if the failed tests will not pass after re-running the jobs. 

However, I now have a few minor requests to update this PR:

- Since you have disabled the passive wave feature, can you change the title of the folder to along the lines of `Multiple_Waves`
- Update the `README.md` to reflect the changes in what this applications case is demonstrating.

If you can please make these changes and the tests pass then we should be able to merge.

**Comment by salhus** [comment]
@nathanmtom 
Hi Nathan,

Thanks for the recommendations. I updated the folder-name and the readme.md file.

Cheers,
Sal

**Review by kmruehl — APPROVED** [review]

**Comment by nathanmtom** [comment]
@akeeste @kmruehl I see that @kmruehl approved this PR but we still have tests failing. Are we accepting these failed tests for the moment, or do @salhus and I need to dive further into resolving conflicts? I just want confirmation as the application and documentation are approved on my end but want to ensure we are providing the right tests.

**Comment by akeeste** [comment]
Hi @nathanmtom 

It looks like all of the failing tests were occurring previously. As long as the current ``Test_NWaves`` is passing, I think we should merge this. Then Kelley and I can continue working through the issues on dev.

The last thing to add the tests to the CI suite, which you can do by adding the application's folder to Lines 48-26 of the [``run-tests-dev.yml`` file](https://github.com/WEC-Sim/WEC-Sim_Applications/blob/dev/.github/workflows/run-tests-dev.yml). I worked on documenting this process last week but don't have it pushed yet.

**Comment by akeeste** [comment]
@nathanmtom I'm going to merge this PR then add the test to GitHub Actions and solve any other issues in #49

**Pull request merged**
