### PR TITLE
Update WECCCOMP to reflect changes in wave gauge implementation.

### PR DESCRIPTION
**Pull request by nathanmtom**
This pull request updates the WECCCOMP_Fault_Implementation input files to reflect the changes made to the wave gauge implementation per WEC-Sim PR https://github.com/WEC-Sim/WEC-Sim/pull/801.

### CODE REVIEW

**Comment by H0R5E** [comment]
Note that WECCCOMP test is now skipped following merging of #21, and [this line](https://github.com/WEC-Sim/WEC-Sim_Applications/blob/11623cd49c29eed345b77eddf7cdde7ecf1f0e56/WECCCOMP_Fault_Implementation/TestWECCOMP.m#L53) needs to be deleted to re-implement them.

**Comment by kmruehl** [comment]
Thanks @nathanmtom I'm going to make some minor changes to this due https://github.com/WEC-Sim/WEC-Sim/pull/803 being merged.

**Comment by kmruehl** [comment]
@nathanmtom and  @salhus I still can't figure out the issue is with this case. The WaveMarker case is working with [WEC-Sim dev](https://github.com/WEC-Sim/WEC-Sim/tree/dev), but I can't seem to get this one working. Any thoughts?

**Comment by kmruehl** [comment]
@nathanmtom I'm going to close this PR and merge it into PR #17  to work on debugging

**Pull request closed without merging**
