### PR TITLE
Addition of a mean drift application case for a sphere

### PR DESCRIPTION
**Pull request by nathanmtom**
This is the first attempt at adding a mean drift application to the WEC-Sim applications folder. 

- [x] The forces from WAMIT have been checked.
- [x] readWAMIT imports the mean drift force from the .out file for all six degrees of freedom and there seems to be sufficient justification to support at this time.

### CODE REVIEW

**Comment by kmruehl** [comment]
@nathanmtom and @akeeste is this one ready for a merge now that we've merged PR https://github.com/WEC-Sim/WEC-Sim/pull/800?

**Comment by nathanmtom** [comment]
@kmruehl If @akeeste is able to run the WEC-Sim example successfully, then it should be okay to merge once I add a readMe file which I have just remembered needs to be added.

**Comment by kmruehl** [comment]
Should this PR go into `dev` too, like PR 800?

**Comment by nathanmtom** [comment]
@kmruehl If the team would prefer, I can submit a pull request to `dev` and delete the PR to `master.` Unless I hear differently in the next few hours, I'll proceed with this process.

**Comment by kmruehl** [comment]
@nathanmtom you should just be able to edit the PR and change the base to dev without closing and re-opening the PR

**Comment by akeeste** [comment]
@nathanmtom I think this case is complete now. I can successfully recreate the WAMIT output and run the case with the userDefinedFunctions. The only issue is that since this branch was changed from master to dev there are some extra files being included in the PR (input files, tests, etc) We might need to copy this new case to a new PR to avoid those extra files.

**Comment by kmruehl** [comment]
@akeeste I can try to clean that up and merge this PR now

**Pull request merged**
