### PR TITLE
BUGFIX: Desalination Application

### PR DESCRIPTION
**Pull request by kmruehl**
Resolving https://github.com/WEC-Sim/WEC-Sim/issues/918

Tests pass locally, not sure why they don't pass on the runner

### CODE REVIEW

**Comment by kmruehl** [comment]
@H0R5E any thoughts on what could be causing this issue?

**Comment by H0R5E** [comment]
@kmruehl, I can't test this locally, as I don't have a Simscape Fluids license. Can you retrigger the workflow? It was such a long time since it was last run that maybe something has changed with the MATLAB runners.

**Comment by H0R5E** [comment]
OK, getting a more informative error now:

```
  ================================================================================
  Error occurred in TestDesalination/testDesalination and it did not run to completion.
      ---------
      Error ID:
      ---------
      'SL_SERVICES:utils:STD_EXCEPTION'
      --------------
      Error Details:
      --------------
      Error using wecSim
      STD exception 'pmf::PreFormattedMessageException': 'Could not open file
      /home/runner/.matlab/R2022b/thisMatlab.pem. No such file or directory.' was
      caught.
      
      Error in TestDesalination/testDesalination (line 54)
                  wecSim
  ================================================================================
```

This looks like a permissions problem, so it's something to do with the MATLAB runner. I'll open an issue about it tomorrow.

**Comment by kmruehl** [comment]
The desal test case was failing locally, so I updated the slx case file. The desal test now passes locally, so let's see if that resolves the issue remotely.

**Comment by kmruehl** [comment]
refer to discussion here: https://github.com/WEC-Sim/WEC-Sim/issues/918

The desal tests pass locally, but I was unable to resolve the issue on the runner. So, I went ahead and removed the desal test from the runner. It'll only be running locally from now on.

**Pull request merged**
