### PR TITLE
BEMIO updates

### PR DESCRIPTION
**Pull request by akeeste**
This PR makes BEMIO renaming updates to complement WEC-Sim/WEC-Sim#790 and WEC-Sim/WEC-Sim#812

### CODE REVIEW

**Comment by kmruehl** [comment]
@akeeste let's create a dev branch and submit this PR into dev (since the current BEMIO updates are on dev). Also, please revert the clear all close all commit. It's helpful for BEMIO since we nearly always name the structure hydro, and overwriting it without clearing can cause issues.

**Comment by akeeste** [comment]
@kmruehl How about we change this to ``clear hydro``? I find it frustrating when I run a BEMIO script and it ends up clearing everything in my workspace, the command window and all plots. There were some other cases in the WEC-Sim repo we have updated too

**Comment by akeeste** [comment]
@kmruehl I still think we have a broader issue with often clearing the command window and all plots without discretion, but the commands are restored in these bemio scripts. Its merged with dev now.

**Review by kmruehl — APPROVED** [review]
Thanks for updating the write h5 example

**Pull request merged**
