### PR TITLE
Update MoorDyn and Paraview examples to be compatible with new MoorDyn v2 format

### PR DESCRIPTION
**Pull request by jtgrasb**
This PR goes along with WEC-Sim [PR#1212](https://github.com/WEC-Sim/WEC-Sim/pull/1212/) to update the RM3 MoorDyn examples to be compatible with the new v2 capabilities and format. This includes updating both the Mooring/MoorDyn example and the Paraview_Visualization\RM3_MoorDyn_Viz example.

### CODE REVIEW

**Comment by H0R5E** [comment]
@jtgrasb, I added the Mooring folder into the Windows tests today, which is why this PR is failing now. I tried to merge in the changes on the `dev` branch, but that didn't help (maybe made it worse?). 

The errors it's throwing are:

```
Failed to find 'WECSim_Lib_Moorings/MoorDynCaller' in library 'WECSim_Lib_Moorings' referenced by 'RM3MoorDyn/MoorDynCaller'
Failed to find 'WECSim_Lib_Moorings/MoorDynConnection' in library 'WECSim_Lib_Moorings' referenced by 'RM3MoorDyn/MoorDynConnection'
```

The test is working on the `dev` branch, so I'm not sure what has happened here, Sorry.

**Comment by H0R5E** [comment]
@jtgrasb 

> it is expected that the mooring tests will fail until that PR is merged into dev

Thanks for the heads up!

**Comment by jtgrasb** [comment]
@dav-og I've attached a zip file with the results from the old version. You can use it to compare to the new version. 

As for the testing, the tests are already set up to load in the MoorDyn repository to run the applications case. One thing that will need to be addressed at some point is the operating system we test it on (MD has different files for windows, linux, and mac), but I think this can be revisited with all the rest of the tests.

[MD_old_results.zip](https://github.com/WEC-Sim/WEC-Sim_Applications/files/14668842/MD_old_results.zip)

**Comment by dav-og** [comment]
Awesome! Thanks Jeff! 👍

**Comment by Student-hub-svg** [comment]
Hello, I encountered the following error when running the latest version of WEC-Sim_Applications\Mooring\MoorDyn in MATLAB: Could you provide detailed step-by-step instructions to run it correctly?

Failed to find 'WECSim_Lib_Moorings/MoorDynCaller' in library 'WECSim_Lib_Moorings' referenced by 'RM3MoorDyn/MoorDynCaller'
Failed to find 'WECSim_Lib_Moorings/MoorDynConnection' in library 'WECSim_Lib_Moorings' referenced by 'RM3MoorDyn/MoorDynConnection'

**Comment by jtgrasb** [comment]
@Student-hub-svg Please make sure your WEC-Sim/WEC-Sim version is updated to the latest version. Then, make sure MATLAB and Simulink are refreshed to reload the Mooring library. This should ensure the model finds the new blocks.

**Comment by Student-hub-svg** [comment]
I'm currently using the latest version of WECSim, with MATLAB R2023b. I've also installed Moordyn-2.4.0-win64.exe into WEC-Sim\source\functions\MoorDyn. However, when I run wecSim under WEC-Sim_Applications\Mooring\MoorDyn, those two errors still pop up. Is there any way to fix this? @jtgrasb

**Comment by jtgrasb** [comment]
@Student-hub-svg The issue you're having is with the Mooring library in WEC-Sim. I would recommend opening the library file (source/lib/WEC-Sim/WECSim_Lib_Moorings.slx) and making sure you see the two blocks MoorDynCaller and MoorDynConnection. If you don't see these two blocks, the library needs to be replaced with the latest version. If you do see these two blocks and still get this issue, than for some reason Simulink is not loading them correctly. If you're still getting this issue please create a new issue and attach a zip with  your WEC-Sim setup.

**Comment by Mint620** [comment]
Hello, when I was trying to add these two blocks in to the example but always find this issue:

Error using responseClass/loadMoorDyn (line 372)
Incorrect use of '=' operator. '=' is used for variable assignment, while '==' is used to compare values for equality.

Error in postProcessWecSim (line 148)
output.loadMoorDyn(mooring(iMoor).moorDynLines, mooring(iMoor).moorDynInputFile, iMoor, mooringLineCount);

Error in stopWecSim (line 29)
postProcessWecSim

Error in run (line 112)
evalin('caller', strcat(scriptStem, ';'));

Error in wecSim (line 55)
run('stopWecSim');

Can I ask how to solve this?

**Pull request merged**
