### PR TITLE
Nlcontrol

### PR DESCRIPTION
**Pull request by glennond**
Fuzzy Logic control example for ALFA Task 11 nonlinear PTO control strategy. The first example to incorporate into WEC-Sim_Applications for milestone M11.3.4. A supervisory Fuzzy Logic controller implementing over-travel protection for RM3 over a linear damping control strategy.

### CODE REVIEW

**Comment by dforbush2** [comment]
@glennond I have been reviewing your pull request. Please ensure that you have pushed the most recent commit, as the current version does not seem to be complete. In particular there is an incomplete function call on line 152 or RM3/Matlab Function named fuzzyLogicController that seems as though it should contain the aggregation and defuzzification operations associated with the determined membership function. The comments on lines 145, 147, and 149 suggest other functions may be missing as well.

For the purposes of your readme file, it would be nice if there was some discussion or a link to a discussion surrounding the selection of your logic regions in the context of the RM3 device/wave state so that users familiar with fuzzy logic who seek to modify the applications case have some guidance.

**Comment by dforbush2** [comment]
Hi @glennond , thank you for your pull request. I have been reviewing it and have several (minor) requests prior to merging, and a couple of requests for the readMe file. I am not an expert in fuzzy logic control so please forgive any misunderstanding on my part:

1) Please remove all commented lines of code in RM3_FLC/fuzzyLogicController. However, the explanatory comments are commended and encouraged! 
2) Please revise the explanatory comments for clarity, in particular please write out acronyms at first appearance, or define them in the readMe file.
3) Delete or address the comments on line 612 and 810.
4) To add utility to the applications case please consider replacing hard-coded methods or parameters as function inputs defined in wecSimInputfile. For example, the second argument to 'defuzzify, the damping range, and line 131. This will also help reduce simulation time as these parameters are currently redefined every time step.
5) It is generally advisable to avoid 'find' functions in simulink blocks as they are unsupported by some code compilers. A number of these functions are used beginning on line 763. If possible, could you break these over two lines as:
`[~,idx]=max(fullY) ; maximaXs=abs(maxima(Xs(idx)));` 
If this is not possible that is alright.
6) Please delete comments like that on line 763 for clarity.

Also, if you wouldn't mind explaining in the readMe how "optimal" damping was defined in this context, and the value of the constant multiplier in RM3_FLC/Fuzzy Controller, this would add clarity to the model and application.

Thank you!

**Comment by glennond** [comment]
Hi @dforbush2 thanks for the feedback, I'll work on making these changes.

Regarding point 5, I tried to avoid find() wherever possible, but in those instances the max can occur at multiple points, so I needed a vector of indices out, which had unknown length. I can spend some more time trying to figure out a workaround for this.

I think it was the wrong commit initially, most comments are cleaned up in my working version. Unfortunately, I've also found the centroid defuzzification method doesn't work in simulink because it relies on polyshape() which isn't supported for code generation. In addition to the readme, I'm also working on some more examples, and getting the supplementary material in a more conference paper format. I'm thinking I should close this PR and just open a new one when I've got all this done, probably shortly after the PMEC meeting Sept 10th.

**Comment by dforbush2** [comment]
Hi @glennond

With regard to 5, the unknown vector length is precisely the problem. A quick and dirty work around would be to pre-allocate a vector longer than you think you could ever need to contain all the maxima, and then threshold by something like 99% of that value:

allMax=zeros(10,1); % pre-allocation
sortData=sort(data, ‘descending’);  % you can add output arguments to retain the original indices of the sorted points
allMax=sortData(1:10);
highVal=max(allMax);
allMax(allMax<0.99*highVal)=[]; % here we retain only points 99% or greater than the max

(I don’t have matlab in front of me and may have slightly bungled the syntax, but hopefully the idea comes through).

It seemed to me there were several different defuzzification methods coded up? As far as the applications case goes any of these are fine for our purposes, doesn’t necessarily have to be the centroid method.

Thank you,
Dominic

**Pull request closed without merging**
